### ISSUE TITLE
Subdomain for community translations - suggestions welcome

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/community-translations-standard#41]
We put the main standard at www.standardforpubliccode.org
Just fixed the translations page (layout was broken). Now thinking: it is still at https://standard-for-public-code.github.io/community-translations-standard/

Maybe needs to go to translations.standardforpubliccode.org or something; Any suggestions?

**Comment by jgroenen** [comment]
Other options IMO are:
- i18n.standardforpubliccode.org
- international.standardforpubliccode.org (has a ring to it)

**Comment by jgroenen** [comment]
Working: https://translations.standardforpubliccode.org/

**Comment by ElenaFdR** [comment]
For a better late than never comment: translations (instead of i18n or international) will almost certainly have better SEO, since it's the most self-explanatory, and the closest fit to the question a person might ask ("is there a Tagalog translation of the Standard for Public Code?").
