### ISSUE TITLE
Add "technical debt" to the glossary

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/community-translations-standard#48]
When translating to Dutch we found that "technical debt" is a jargon term. Can we add it to the glossary, or is there a reason to keep it out?

**Comment by ericherman** [comment]
I think the best idea would be to find a way to re-phrase the sentences in order to avoid the jargon.

Alternatively, adding to the glossary is fine.

**Comment by jgroenen** [comment]
In the Dutch translation we also removed the term.
