### ISSUE TITLE
Chinese criteria page is empty

### ISSUE THREAD

**Issue by Ainali** [standard-for-public-code/community-translations-standard#58]
The site seem to have built, but the page for [criteria](https://translations.standardforpubliccode.org/zh_Hant_TW/criteria/) is empty.

**Comment by clausmullie** [comment]
Curious, this is with the current theme, so that means it's not related to [this fix](https://github.com/standard-for-public-code/jekyll-theme/pull/10) but a separate issue. That means we could go ahead and merge that fix, and figure this out as a separate issue.
